# Site Settings
title: Mae Sliwinski
name: Mae Sliwinski
description: Mae Sliwinski – Projects and CV
url: "https://maesliwinski.github.io"
baseurl: ""

theme: jekyll-theme-minimal

markdown: kramdown

# Optional styling
color_scheme: light

plugins:
  - jekyll-seo-tag
